version: '3'
services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
     - "9090:9090"
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"


